# Generated by Django 3.1 on 2021-06-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20210614_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='jpgfile',
            field=models.FileField(upload_to='images'),
        ),
    ]
