# Generated by Django 3.1 on 2021-06-14 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20210614_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Jpgimage',
        ),
    ]
