# Generated by Django 3.1 on 2021-06-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20210614_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pngimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pngfile', models.FileField(upload_to='images')),
            ],
        ),
    ]
